### ISSUE TITLE
Glitch when using forward slashes in your QuantConnect folders i.e. /Research

### ISSUE THREAD

**Issue by cnaccio** [QuantConnect/quantconnect-cli#8]
I accidentally realized that if you add a forward slash to the beginning of a folder name in QuantConnect, this will cause an error when trying to pull that folder down using qcli. Although it doesn't seem to matter to QuantConnect whether or not your folder starts with a / or not; qcli tries to use that forward slash while making the local directories. Took me a bit to figure out what was going on, but simply removing the forward slash in QuantConnect solved my issue. Not sure it's worth a fix, but maybe some documentation on it as a known issue could help others.

**Comment by jmerle** [comment]
Fixed in https://github.com/QuantConnect/quantconnect-cli/commit/2347c00dee75cc29d5d0a3d78e0af3ac2abb4118, I have fixed it so that a project called `/Research/Project` is synchronized to `./Research/Project` and can be referenced in CLI commands as both `/Research/Project` as well as `Research/Project` (or even `///Research/Project` if you like that, all leading forward slashes are ignored).

**Comment by jmerle** [comment]
Released in [1.4.4](https://github.com/QuantConnect/quantconnect-cli/releases/tag/v1.4.4).
